language: python

sudo: false

python:
- '2.4'
- '2.7'
- '3.3'
- '3.4'
- '3.5'

install:
  - pip install tox pycodestyle nose coverage unittest2

script:
  - tox

after_success:
  - nosetests --with-coverage --cover-package=cloudipsp