language: python

sudo: false

env:
  - TOXENV=py24
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

install:
  - pip install tox pycodestyle nose coverage unittest2 requests

script:
  - tox

after_success:
  - nosetests --with-coverage --cover-package=cloudipsp